name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/darkrta/rb3-build:main
    strategy:
      fail-fast: false
      matrix:
        version: [SZBE69_B8]
    if: github.repository_owner == 'DarkRTA'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Prepare
      run: cp -R /orig .
    - name: Build
      run: |
        python configure.py --map --version ${{ matrix.version }} \
            --binutils /binutils --compilers /compilers
        ninja all_source build/${{ matrix.version }}/progress.json \
            build/${{ matrix.version }}/report.json
    - name: Upload progress
      if: github.ref == 'refs/heads/master' && matrix.version == 'SZBE69_B8'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{secrets.PROGRESS_API_KEY}}
      run: |
        python tools/upload_progress.py -b https://progress.decomp.club/ -p rb3 -v ${{matrix.version}} \
          build/${{matrix.version}}/progress.json
    - name: Upload map
      uses: actions/upload-artifact@v3
      with:
        name: ${{matrix.version}}_maps
        path: build/${{matrix.version}}/**/*.MAP
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.version }}_report
        path: build/${{ matrix.version }}/report.json

  build-nonmatching:
    runs-on: ubuntu-latest
    container: ghcr.io/darkrta/rb3-build:main
    strategy:
      fail-fast: false
    if: github.repository_owner == 'DarkRTA'
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Git config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Prepare
      run: cp -R /orig .
    - name: Build
      run: |
        python configure.py --map --version SZBE69_B8 \
          --binutils /binutils --compilers /compilers --wrapper wibo \
          --non-matching
        ninja
    - name: Upload progress
      if: github.ref == 'refs/heads/master'
      continue-on-error: true
      env:
        PROGRESS_API_KEY: ${{secrets.PROGRESS_API_KEY}}
      run: |
        python configure.py progress --version SZBE69_B8 --non-matching
        python tools/upload_progress.py -b https://progress.decomp.club/ -p rb3 -v Equivalent \
          build/SZBE69_B8/progress.json
    - name: Upload map
      uses: actions/upload-artifact@v3
      with:
        name: SZBE69_B8_maps
        path: build/SZBE69_B8/**/*.MAP
